//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planeacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtDetalleTotales
    {
        public int HtConsecutivo { get; set; }
        public int HtNumActividad { get; set; }
        public int HtIdMes { get; set; }
        public int HtAngo { get; set; }
        public int HtNumLinea { get; set; }
        public Nullable<int> HtIdGrupoOcupacional { get; set; }
        public string HtNombre { get; set; }
        public string HtApellido { get; set; }
        public Nullable<int> HtCantidad { get; set; }
        public Nullable<int> HtIdGenero { get; set; }
        public Nullable<int> HtIdTipoContrato { get; set; }
        public string HtCedula { get; set; }
        public Nullable<int> HtIdRubro { get; set; }
        public int HtIdCamino { get; set; }
        public string HtObservaciones { get; set; }
    
        public virtual HtTipoContrato HtTipoContrato { get; set; }
        public virtual HtGenero HtGenero { get; set; }
        public virtual HtGrupoOcupacional HtGrupoOcupacional { get; set; }
        public virtual HtRubro HtRubro { get; set; }
    }
}
