//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planeacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtGenero
    {
        public HtGenero()
        {
            this.HtDetalleTotales = new HashSet<HtDetalleTotales>();
        }
    
        public int HtIdGenero { get; set; }
        public string HtDescripGenero { get; set; }
    
        public virtual ICollection<HtDetalleTotales> HtDetalleTotales { get; set; }
    }
}
